name = "sumi-webhook-local"
vars = { ENVIRONMENT = "local" }

main = "./index.js"
compatibility_date = "2022-11-30"

logpush = true
workers_dev = true
usage_model = "unbound"

kv_namespaces = [
    { binding = "KV_PROD", id = "{{KV_LOCAL_ID}}", preview_id = "{{KV_LOCAL_ID}}" },
]

[env.prod]
name = "sumi-webhook"
vars = { ENVIRONMENT = "prod" }

kv_namespaces = [{ binding = "KV_PROD", id = "{{KV_PROD_ID}}" }]
