name = "sumi-webhook-local"
vars = { ENVIRONMENT = "local" }

type = "javascript"

workers_dev = true
usage_model = "bundled"
compatibility_date = "2022-01-28"

kv_namespaces = [
    { binding = "WEBHOOKS_INFO", id = "{{KV_LOCAL_ID}}", preview_id = "{{KV_LOCAL_ID}}" },
]

[env.prod]
name = "sumi-webhook"
vars = { ENVIRONMENT = "prod" }
kv_namespaces = [{ binding = "WEBHOOKS_INFO", id = "{{KV_PROD_ID}}" }]
