name = "sumi-webhook-local"
vars = { ENVIRONMENT = "local" }

main = "src/index.ts"
compatibility_date = "2022-07-15"

node_compat = true
workers_dev = true
usage_model = "unbound"

kv_namespaces = [
    { binding = "KV_PROD", id = "{{KV_LOCAL_ID}}", preview_id = "{{KV_LOCAL_ID}}" },
]

[env.prod]
name = "sumi-webhook"
vars = { ENVIRONMENT = "prod" }

kv_namespaces = [{ binding = "KV_PROD", id = "{{KV_PROD_ID}}" }]
