name = "sumi-webhook-local"
vars = { ENVIRONMENT = "local" }

main = "./dist/cfworker/index.js"
compatibility_date = "2022-11-30"

logpush = true
workers_dev = true
usage_model = "unbound"

kv_namespaces = [
    { binding = "KV", id = "{{KV_LOCAL_ID}}", preview_id = "{{KV_LOCAL_ID}}" },
]


[[queues.producers]]
queue = "{{QUEUE_NAME_LOCAL}}"
binding = "MESSAGE_QUEUE"

[[queues.consumers]]
queue = "{{QUEUE_NAME_LOCAL}}"
max_batch_size = 10
max_batch_timeout = 1

[env.prod]
name = "sumi-webhook"
vars = { ENVIRONMENT = "prod" }

kv_namespaces = [{ binding = "KV", id = "{{KV_PROD_ID}}" }]

[[analytics_engine_datasets]]
binding = "metricsDataset"

[[queues.producers]]
queue = "{{QUEUE_NAME_PROD}}"
binding = "MESSAGE_QUEUE"

[[queues.consumers]]
queue = "{{QUEUE_NAME_PROD}}"
max_batch_size = 10
max_batch_timeout = 1
