name = "sumi-webhook-local"
vars = { ENVIRONMENT = "local" }

main = "./dist/cfworker/index.js"
no_bundle = true

compatibility_date = "2024-02-21"

logpush = true
workers_dev = true

node_compat = true
compatibility_flags = [ "nodejs_als" ]

kv_namespaces = [
    { binding = "KV", id = "{{KV_LOCAL_ID}}", preview_id = "{{KV_LOCAL_ID}}" },
]

[[analytics_engine_datasets]]
binding = "metricsDataset"

[[queues.producers]]
queue = "{{QUEUE_NAME_LOCAL}}"
binding = "MESSAGE_QUEUE"

[[queues.consumers]]
queue = "{{QUEUE_NAME_LOCAL}}"
max_batch_size = 10
max_batch_timeout = 1

[placement]
mode = "smart"

[env.prod]
name = "sumi-webhook"
vars = { ENVIRONMENT = "prod" }

kv_namespaces = [{ binding = "KV", id = "{{KV_PROD_ID}}" }]

[[env.prod.queues.producers]]
queue = "{{QUEUE_NAME_PROD}}"
binding = "MESSAGE_QUEUE"

[[env.prod.queues.consumers]]
queue = "{{QUEUE_NAME_PROD}}"
max_batch_size = 10
max_batch_timeout = 1

[[env.prod.analytics_engine_datasets]]
binding = "metricsDataset"
