name = "sumi-webhook-local"
vars = { ENVIRONMENT = "local" }

main = "src/index.ts"
compatibility_date = "2022-07-15"

node_compat = true
workers_dev = true
usage_model = "unbound"

[env.prod]
name = "sumi-webhook"
vars = { ENVIRONMENT = "prod" }
