name = "sumi-webhook-dev"
vars = { ENVIRONMENT = "dev" }

type = "javascript"

workers_dev = true
compatibility_date = "2022-01-28"

[env.dev]
name = "sumi-webhook-dev"
vars = { ENVIRONMENT = "dev" }

[env.pre]
name = "sumi-webhook-pre"
vars = { ENVIRONMENT = "pre" }

[env.prod]
name = "sumi-webhook"
vars = { ENVIRONMENT = "prod" }
