export default [
  'DINGTALK_SECRET',
  'DINGTALK_WEBHOOK_URL',
  'DINGTALK_OUTGOING_TOKEN',
  'GH_WEBHOOK_SECRET',
  'GH_APP_ID',
  'GH_APP_CLIENT_ID',
  'GH_APP_CLIENT_SECRET',
  'GH_APP_WEBHOOK_SECRET',
  'GH_APP_PRIVATE_KEY',
];
