declare const DINGTALK_SECRET: string;
declare const DINGTALK_WEBHOOK_URL: string;
declare const DINGTALK_OUTGOING_TOKEN: string;
declare const GH_WEBHOOK_SECRET: string;
declare const GH_APP_ID: string;
declare const GH_APP_CLIENT_ID: string;
declare const GH_APP_CLIENT_SECRET: string;
declare const GH_APP_WEBHOOK_SECRET: string;
declare const GH_APP_PRIVATE_KEY: string;