name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  KV_LOCAL_ID: ${{ secrets.KV_LOCAL_ID }}
  KV_PROD_ID: ${{ secrets.KV_PROD_ID }}
  QUEUE_NAME_LOCAL: ${{ secrets.QUEUE_NAME_LOCAL }}
  QUEUE_NAME_PROD: ${{ secrets.QUEUE_NAME_PROD }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Test
        run: |
          yarn
          yarn run build
          yarn run test
