name: Test & Deploy to Pre

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: pre
    name: Test & Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Test
        run: |
          yarn
          yarn run build
          yarn run test
        env:
          KV_LOCAL_ID: ${{ secrets.KV_LOCAL_ID }}
          KV_PROD_ID: ${{ secrets.KV_PROD_ID }}
      - name: Deploy to Pre
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: yarn build
          command: publish
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
