name: Deploy to Pre

on:
  workflow_dispatch:

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  KV_LOCAL_ID: ${{ secrets.KV_LOCAL_ID }}
  KV_PROD_ID: ${{ secrets.KV_PROD_ID }}
  QUEUE_NAME_LOCAL: ${{ secrets.QUEUE_NAME_LOCAL }}
  QUEUE_NAME_PROD: ${{ secrets.QUEUE_NAME_PROD }}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: pre
    name: Test & Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Test
        run: |
          yarn
          yarn run build
          yarn run test

      - name: Deploy to Pre
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: yarn build
          command: publish
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
