name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Test
        run: |
          yarn
          yarn run build
          yarn run test
        env:
          KV_LOCAL_ID: ${{ secrets.KV_LOCAL_ID }}
          KV_PROD_ID: ${{ secrets.KV_PROD_ID }}
